### ISSUE TITLE
Page not found on Refresh

### ISSUE THREAD

**Issue by bhavesh2699** [adrianhajdin/project_chat_application#11]
After creating the room and if refresh the page it shows "page not found".

**Comment by akshaybhat301094** [comment]
to solve this issue make a _redirects file in the build folder for client app and paste the following inside it `/*    /index.html   200` and then redeploy.

here is the documentation link for your reference 
[https://docs.netlify.com/routing/redirects/rewrites-proxies/#limitations](url)

**Comment by akshaybhat301094** [comment]
after adding it you can add the following inside your package.json
`"postbuild": "cp _redirects ./build/"`

**Comment by bhavesh2699** [comment]
Thanks a lot @akshaybhat301094 , Your suggestion worked for me.
