### ISSUE TITLE
Multiple users with same name in the same room

### ISSUE THREAD

**Issue by Sid22031998** [adrianhajdin/project_chat_application#18]
clients -> src -> components -> join -> join.js

line: <Link onClick={event => (!name || !room) ? event.preventDefault() : null} to={`/chat?name=${name}&room=${room}`}>

Can you recommend a method to check whether the user name is present in the same room or not, if present then redirect it to the home page with an alert "Enter another name for the room" or assign a different name to the same user?
The thing is if two users with the same name are joining the same room then the app gets crashed.

**Comment by fransiskusferdian** [comment]
it was explained in https://www.youtube.com/watch?v=ZwFA3YMfkoc  on 56:01

**Comment by Sid22031998** [comment]
Yeah, there was a typo in my code and btw I was asking about redirecting if there is an error.
