### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by ujjawal-1999** [adrianhajdin/project_chat_application#6]
The app stops working in the production environment. The console states,"No Access-Control-Allow-Origin".

**Comment by shashwatshaurya** [comment]
It is a **CORS** issue. Do learn more about it. For the solution of this issue, try again after requiring 'cors' in the index.js file on the server side.

**Comment by ujjawal-1999** [comment]
The CORS middleware has been set up properly. Still, it shows the same error.

**Comment by dpatel017** [comment]
try following...
in chat.js file replace ENDPOINT const with server url ...
const ENDPOINT = 'http://localhost:5000/';//'https://project-chat-application.herokuapp.com/';

**Comment by ujjawal-1999** [comment]
This has been updated but it still has the same error.

**Comment by Robspin** [comment]
FYI I had the same cors error and it turned out to be a typo...

**Comment by Terrance-McGhee** [comment]
Any luck with this error? I'm getting this same error and i have cores enabled

**Comment by SumnanAzadi** [comment]
Still having the CORS issue. I tried adding header and everything but nothing is working

**Comment by philosofonusus** [comment]
same

**Comment by rani-sikdar** [comment]
use a chrome extension to avoid CORS errors. link-
https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf/related

below is a short tutorial for using it-
https://youtu.be/KruSUqLdxQA

**Comment by DUDY206** [comment]
Replace this line in **index.js**
```
const io = require('socket.io')(server,{
    cors:{
        origin:'*',
    }
});
```

**Comment by ankit31969** [comment]
Anyone who was able to solve the cors issue???

**Comment by smbakhal** [comment]
> Replace this line in **server/index.js**
> 
> ```
> const io = require('socket.io')(server,{
>     cors:{
>         origin:'*',
>     }
> });
> ```

yup this helped me

**Comment by jartywizard** [comment]
> > Replace this line in **server/index.js**
> > ```
> > const io = require('socket.io')(server,{
> >     cors:{
> >         origin:'*',
> >     }
> > });
> > ```
> 
> yup this helped me

SAME!!
